[project]
authors = ["Fuel Labs Inc."]
entry = "main.sw"
license = "Apache-2.0"
name = "swaypad"

[dependencies]
src3 = "0.8.1"
src5 = "0.8.1"
src6 = "0.8.1"
src7 = "0.8.1"
src10 = "0.8.1"
src11 = "0.8.1"
src12 = "0.8.1"
src14 = "0.8.1"
src15 = "0.8.1"
src16 = "0.8.1"
src17 = "0.8.1"
src20 = "0.8.1"
admin = "0.26.1"
asset = "0.26.1"
big_int = "0.26.1"
bytecode = "0.26.1"
merkle = "0.26.1"
ownership = "0.26.1"
pausable = "0.26.1"
queue = "0.26.1"
reentrancy = "0.26.1"
signed_int = "0.26.1"
upgradability = "0.26.1"
