/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.31.0
  Forc version: 0.32.2
  Fuel-Core version: 0.17.1
*/

export type { SwaypadAbi } from './SwaypadAbi';

export { SwaypadAbi__factory } from './factories/SwaypadAbi__factory';
