name: Frontend - Build and Test

on:
  push:
    branches-ignore:
      - master

env:
  NODE_VERSION: '16'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm ci and build
        env:
          CI: true
        run: |
          cd app && npm ci && npm run build
          cp -r build ../build
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path .
      - name: npm test
        run: |
          sway-playground & # Start sway-playground in the background
          cd app && npm run test
