name: Frontend - Build and Test

on:
  push:
    branches-ignore:
      - master

env:
  NODE_VERSION: '16'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/fuellabs/sway-playground
          tags: |
            type=ref,event=branch
            type=sha,prefix=
            type=semver,pattern={{raw}}
      - uses: actions/checkout@v2
      - name: npm ci and build
        env:
          CI: true
        run: |
          cd app && npm ci && npm run build
          cp -r build ../build
      - run: echo ${{ steps.meta.outputs }}
      - uses: addnab/docker-run-action@v3
        with:
          image: ${{ steps.meta.outputs.tags }}
      - name: npm test
        run: |
          cd app && npm run test
