name: Frontend - Build and Test

on:
  push:
    branches-ignore:
      - master

env:
  NODE_VERSION: '16'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm ci and build
        env:
          CI: true
        run: |
          cd app && npm ci && npm run build
          cp -r build ../build

    steps:
      - uses: actions/checkout@v2
      - name: npm test
        run: |
          cargo run
          cd app && npm run test

