name: Frontend - Build and Test

on:
  push:
    branches-ignore:
      - master

env:
  NODE_VERSION: '16'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      fuel-core:
        image: ghcr.io/fuellabs/sway-playground
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v2
      - name: npm ci and build
        env:
          CI: true
        run: |
          cd app && npm ci && npm run build
          cp -r build ../build
      - name: npm test
        run: |
          cd app && npm run test
